function ret = compute_res_statistics(fid1, id, file, soldif)

    ret =1;
    
    fprintf(fid1,'%34s,hpos, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.2f, %5d\n',...
    file(id).rovfile,soldif.hor_pos_fix(1),soldif.hor_pos_fix(2),soldif.hor_pos_fix(3), soldif.hor_pos_fix(4)...
                     ,soldif.hor_pos_flt(1),soldif.hor_pos_flt(2),soldif.hor_pos_flt(3),soldif.hor_pos_flt(4)...
                     ,soldif.hor_pos_all(1),soldif.hor_pos_all(2),soldif.hor_pos_all(3),soldif.hor_pos_all(4),soldif.fixrate*100.0,soldif.num_all); 
                 
    fprintf(fid1,'%34s,vpos, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.3f, %6.2f, %5d\n',...
    file(id).rovfile ,soldif.ver_pos_fix(1),soldif.ver_pos_fix(2),soldif.ver_pos_fix(3), soldif.ver_pos_fix(4)...
                     ,soldif.ver_pos_flt(1),soldif.ver_pos_flt(2),soldif.ver_pos_flt(3),soldif.ver_pos_flt(4)...
                     ,soldif.ver_pos_all(1),soldif.ver_pos_all(2),soldif.ver_pos_all(3),soldif.ver_pos_all(4),soldif.fixrate*100.0,soldif.num_all); 
%                  
%     fprintf(fid1,'%34s- vel %6.3f %6.3f %6.3f %6.3f %6.3f %6.3f %6.3f %6.3f\n',...
%     file(id).rovfile,soldif.hor_vel_err(1),soldif.hor_vel_err(2),soldif.hor_vel_err(3),soldif.hor_vel_err(4)...
%                      ,soldif.ver_vel_err(1),soldif.ver_vel_err(2),soldif.ver_vel_err(3),soldif.ver_vel_err(4)); 
end 